### ISSUE TITLE
The MPI parallelized efficiency problem running on ARM machine

### ISSUE THREAD

**Issue by lj-cug** [warwick-hpsc/MG-CFD-app-OP2#44]
Dear Sir:
    I have submitted one issue on OP2 repository, also put my problem here. And I wish some buddy can help me.
   Today I have run the airfoil case on the ARM machine, OK! Both the airfoil_openmp and airfoil_mpi can speedup the calculation. The wallclock time is 370.34 (s), 7.03(s), 27.16 (s) (using mpirun -np 16) for sequential, openmp and mpi cases running. 
    Now the problem happened for MG-CFD case running, the mpi parallelism cannot work well. All the MGCFD cases can run normally, but the MPI efficiency cannot work well on the ARM machine. The difference between and airfoil and MGCFD is the multi-grid algorithm. When I use only one level mesh for MGCFD, the same problem still happened. But the MPI version of MGCFD can work well in my X86 machine.

**Comment by lj-cug** [comment]
The most time consumption kernels are compute_flux_edge_kernel and also the simple kernel "get_min_dt_kernel"
![mgcfd_mpi_node=4,N=32 ](https://user-images.githubusercontent.com/53997605/184303402-dbe102bb-e547-4c25-8b58-c0d9fc9a58b6.png)

**Comment by reguly** [comment]
The same people would be answering here as https://github.com/OP-DSL/OP2-Common/issues/232 so I'm closing this.
